config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  get '/dashboard' => 'dashboard#show'

  get '/pages' => 'pages#index'
  get '/pages' => 'pages#new'
  post '/pages' => 'pages#create'
  patch '/pages' => 'pages#update'
  delete '/pages/:id' => 'pages#delete'

  get '/tweets' => 'tweets#index'
  get '/charts' => 'charts#show'

  namespace :api do
    namespace :v1 do
      get '/tweets' => 'tweets#index'

      get '/mentions' => 'mentions#index'
      
      get '/pages' => 'pages#index'
      get '/pages/:id' => 'pages#show'
      post '/pages' => 'pages#create'
    end
  end
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :tweets, only: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get '/:id' => "shortener/shortened_urls#show"
  
 
  root to: 'home#show'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/controllers/api/v1/tweets_controller.rb
class Api::V1::TweetsController < ApplicationController
  def index
    if current_user
      options = {count: 100, include_rts: true}
      @tweets = current_user.client.user_timeline(current_user.twitter_handle, options)
      render 'index.json.jbuilder'     
    else
      redirect_to '/'
    end  
  end 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  attr_accessor :image, :page

  def index
  end

  def new
    page = Page.find_by(id: params[:id])
    if page
      @message = page.title + ' ' + page.short_url
      @image = page.image
      @page_id = page.id 
    else
      @message = ''
      @image = ''
      @page_id = 0
    end
    
  end

  def create
    page = Page.find_by(id: params[:page_id])
    if page
      page.update(status: 'sent')
    end

    if params[:image] == 'true'
      current_user.tweet_with_image(twitter_params[:message], page.image)
    else
      current_user.tweet(twitter_params[:message])
    end
    flash[:success] = 'Sweet! Your tweet has been sent!!'
    redirect_to '/pages'
  end

  def twitter_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/create.html.erb
<h1>Success!</h1>
<p>Your tweet has been sent!</p>
<%= link_to "Would you like to send another?", new_tweet_path %>

app/views/tweets/index.html.erb
 <div ng-app="app" class="content-wrapper">
  <div ng-controller="tweetsCtrl" ng-init="setup()">
    <h1>Recent Tweets</h1>
    <div class="list-group">
      <div class="list-group-item" style='background-color:#F9FAFB'>
        <table class="wd-wide">
          <tbody>
            <tr class='tweet-menu'>
              <td class="wd-xs">
                <div class="ph">
                  <p class="m0">Image</p>
                </div>
              </td>
              <td>
                <div class="ph">
                   <p class="m0" ng-click="changeOrderAttribute('text')">Text</p>
                </div>
              </td>
              <td class="wd-sm hidden-xs hidden-sm">
                <div class="ph">
                  <p class="m0" ng-click="changeOrderAttribute('created_on')">
                    <a href="javascript:void(0)"> Date</a>
                  </p>
                </div>
              </td>
              <td class="wd-xs hidden-xs hidden-sm">
                <div class="ph">
                  <p class="m0" ng-click="changeOrderAttribute('retweet_count')">
                    <a href="javascript:void(0)"> Retweets</a>
                  </p>
                </div>
              </td>
              <td class="wd-xs hidden-xs hidden-sm">
                <div class="ph">
                  <p class="m0" ng-click="changeOrderAttribute('favorites_count')">
                    <a href="javascript:void(0)"> Favorites</a>
                  </p>
                </div>
              </td>
              <td class="wd-sm">
                <div class="ph">
                   <progressbar value="80" type="success" class="m0 progress-xs" ng-click="changeOrderAttribute('rank')">
                    <a href="javascript:void(0)"> Sweetness</a>
                   </progressbar>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div style='height:20px'>      
    </div>
    <div class="list-group" ng-repeat="tweet in tweets | orderBy:orderAttribute:sortDir | limitTo:30">            
      <a href="#" class="list-group-item">
        <table class="wd-wide">
          <tbody>
            <tr>
              <td class="wd-xs">
                <div class="ph" ng-if="tweet.media[0].media_url">
                  <img style='border-color:green' src="{{ tweet.media[0].media_url }}" class="media-box-object img-responsive img-rounded thumb64">
                </div>
              </td>
              <td>
                <div class="ph">
                  <small class="text-muted">{{ tweet.text }}</small>
                </div>
              </td>
              <td class="wd-sm hidden-xs hidden-sm">
                <div class="ph">                               
                  <small class="text-muted">{{ tweet.created_at | date : format : 'M' }}</small>
                </div>
              </td>
              <td class="wd-xs hidden-xs hidden-sm">
                <div class="ph">
                  <p class="m0 text-muted">
                    {{ tweet.retweet_count }}
                  </p>
                </div>
              </td>
              <td class="wd-xs hidden-xs hidden-sm">
                <div class="ph">
                  <p class="m0 text-muted">{{ tweet.favorites_count }}</p>
                </div>
              </td>
              <td class="wd-sm">
                <div class="ph">
                  <progressbar value="80%" type="success" class="m0 progress-xs">{{ tweet.favorites_count + (tweet.retweet_count * 2) }}</progressbar>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </a>
    </div>
  </div>  
</div>

app/views/tweets/new.html.erb
<div class='row' ng-app="app">
  <div ng-controller="tweetsCtrl">
    <div class='composer col-xs-12 col-md-4'>
      <h2>Tweet Composer</h2>
      <%= form_for :tweet, url: "/tweets?page_id=#{@page_id}&image=true", html: {id: 'tweet-form' } , method: :post do |f| %>
        <%= f.text_area :message, 
                        :value => @message, 
                        "ng-init" => "message='#{@message}'; addCount();", 
                        "ng-model" => "message", 
                        "ng-change" => "changeCount()"  
        %>
        <div class='added-image'>
          <img id='image-thumb' class='hidden' src="<%= @image %>">
        </div>
        <div>
          <%= f.submit "Send Tweet", style: 'display:inline', id: 'submit-tweet-btn', class: 'btn btn-large btn-success send-tweet' %>
          <input style ='display:none' ng-click="submitAlert()" value="Send Tweet" id="submit-alert-btn" class="btn btn-large btn-warning submit-tweet-alert">
          <div>Characters Left: <span id='word-count'>{{wordCount}}</span></div>
        </div> 
      <% end %>
    </div>
    <div class='tweet-img col-xs-12 col-md-4'>
      <div id='image-preview'>
        <h3>Image Preview</h3>
        <img id='image' src="<%= @image %>">
      </div>
      <button id='add-image' align='center' class='btn btn-large btn-danger' ng-click="addImage()">Add Image</button>
      <button id='remove-image' align='center' class='btn btn-large btn-warning hidden' ng-click="removeImage()">Remove Image</button>
      <input type='hidden' id='image-input' value='false'>
    </div>
  </div>
</div>